---

language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

install: bundle install --jobs=3 --retry=3 --deployment --path vendor/bundle

cache:
  directories:
    - vendor/bundle

script: bundle exec rspec
